# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9837f67a5a565624793420c1965f004eb05f38fbf72c6ef4a4aa02fc8ae6fdf550f38bafe15ca448c3b607b2553836c78a73aa2d149b9ad47ed8165adcd80e95

test:
  secret_key_base: d904709fc43ff236b1c4f40f6a05d766a65cdb9ed903e2ef4079805d0ad2945f5f0487c0832eb162bb4d95cfa4f3700d0a7c6d489466e66dbf21ff559cacf500

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
